#!/bin/bash
# UserPromptSubmit hook: inject the full-cycle directive into every user prompt,
# UNLESS the prompt contains the skip token [quick].
input=$(cat)
prompt=$(printf '%s' "$input" | jq -r '.prompt // empty' 2>/dev/null)
case "$prompt" in
  *'[quick]'*) exit 0 ;;
esac
ctx='[full-cycle enforced] If this request touches files — implementation, changes, bugfixes, refactors, configuration, builds — first invoke the full-cycle skill via the Skill tool and follow the whole pipeline to the end: intent capture -> security/UI·UX&DX/technical tri-axis -> per-Goal Codex research (codex-research skill: both-sides evidence; deep-research only as fallback) -> deep interview (no obvious questions) -> one Goal + milestone + PR-sized task decomposition with per-task deps/files declarations in GOAL.md -> docs/<goal>/GOAL.md + task folders -> conditional design consult -> DAG-scheduled execution (serial default; review rounds of different tasks overlap by default; worker fan-out via general-dev/frontend-dev in git worktrees only on a check-parallel.sh PARALLEL verdict, scope-checked before review and merge; INVALID declarations mean fix the decomposition) -> Red-Green-Refactor TDD -> codex-review (GPT-5.6 Sol; mandatory pre-review defect-class self-sweep with class-wide fixes; one new codex-review-<NNN>.md per round; findings carry evidence + verification, an optional one-line suggested direction only when the repair is non-obvious, no code examples; a round left with only low-severity items closes that round as approve-with-fixes; continue until genuine consensus) -> per-task + per-milestone + final Goal E2E -> final report. Communicate with the user in Korean; write all workflow artifacts and every agent-to-agent prompt/report in English. Only check a Gate-status / Goal-gate checkbox when it is actually complete (while any is unchecked in an active GOAL.md or task doc, the Stop hook blocks the turn from ending). Pure questions / lookups / conversation may skip this.'
jq -n --arg c "$ctx" '{hookSpecificOutput:{hookEventName:"UserPromptSubmit",additionalContext:$c}}'
